<?php
$_prsafe = array (
  'kid' => 'prsafe',
  'pid' => 'score',
  'title' => '安全参数',
  'enable' => '1',
  'etab' => '0',
  'deep' => '1',
  'f' => 
  array (
    'safe_site' => 
    array (
      'kid' => 'safe_site',
      'title' => '全站唯一随机码',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'str:18-48',
      'vtip' => '18~48位',
      'vmax' => '255',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'key' => '[safe][site]',
      'val' => 'name-juxk8-JApbz-ZaQK8-hI3eZ-RgNmG',
    ),
    'safe_pass' => 
    array (
      'kid' => 'safe_pass',
      'title' => '密码加密-混淆码',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'str:18-48',
      'vtip' => '18-48位',
      'vmax' => '255',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'key' => '[safe][pass]',
      'val' => 'pass-CxRSS-nfGVd--Zxgo-1uqHF-2TquM',
    ),
    'safe_adminer' => 
    array (
      'kid' => 'safe_adminer',
      'title' => 'm混淆码-adminer',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'str:18-48',
      'vtip' => '18-48位',
      'vmax' => '255',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'key' => '[safe][adminer]',
      'val' => 'adm-KBvyG-YmWFs-Oqw7u-Yyqyv-@UPz+',
    ),
    'safe_api' => 
    array (
      'kid' => 'safe_api',
      'title' => 'API-随即码',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'str:18-48',
      'vtip' => '18~48位',
      'vmax' => '255',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'key' => '[safe][api]',
      'val' => 'api-OZiZv-AwDrm-71yUJ-doCp1-fsq2X',
    ),
    'safe_js' => 
    array (
      'kid' => 'safe_js',
      'title' => 'JS-随即码',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'str:18-48',
      'vtip' => '18~48位',
      'vmax' => '255',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'key' => '[safe][js]',
      'val' => 'js-01Sq9-3uH9D-GPEL2-qBL7U-FdSoX',
    ),
    'safe_other' => 
    array (
      'kid' => 'safe_other',
      'title' => 'Other-其他随机码',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'str:18-48',
      'vtip' => '18~48位',
      'vmax' => '255',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'key' => '[safe][other]',
      'val' => 'other-qjMfL-J1OjS-YIyZB-hHoIl-Uog7l',
    ),
    'safe_safil' => 
    array (
      'kid' => 'safe_safil',
      'title' => '安全过滤-随机码',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'str:18-48',
      'vtip' => '18~48位',
      'vmax' => '255',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'key' => '[safe][safil]',
      'val' => 'safil-s75fR-33DYu-bpluO-bcBDI-HPiNY',
    ),
    'safe_safix' => 
    array (
      'kid' => 'safe_safix',
      'title' => '安全过滤-数组前缀',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'str:4-4',
      'vtip' => '4位',
      'vmax' => '4',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'key' => '[safe][safix]',
      'val' => '_819',
    ),
    'safe_rnum' => 
    array (
      'kid' => 'safe_rnum',
      'title' => '数字-随机码',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'str:18-48',
      'vtip' => '18~48位',
      'vmax' => '255',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'key' => '[safe][rnum]',
      'val' => '355837552898273612412861',
    ),
    'safe_rspe' => 
    array (
      'kid' => 'safe_rspe',
      'title' => '特殊字符-随机码',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '255',
      'dbdef' => '',
      'vreg' => 'str:18-48',
      'vtip' => '18~48位',
      'vmax' => '255',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'key' => '[safe][rspe]',
      'val' => 'hwb-P_)RPRR9-@O2+97O9-nQqRfqqO',
    ),
    'safe_rndch6' => 
    array (
      'kid' => 'safe_rndch6',
      'title' => '随机6位码',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '6',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '6',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'key' => '[safe][rndch6]',
      'val' => 'hH0.hH',
    ),
    'safe_rndtab' => 
    array (
      'kid' => 'safe_rndtab',
      'title' => '随机62位不重复码',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'varchar',
      'dblen' => '62',
      'dbdef' => '',
      'vreg' => '',
      'vtip' => '',
      'vmax' => '62',
      'fmsize' => '360',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'key' => '[safe][rndtab]',
      'val' => 'CjG8Lsr5mJgPElRNMyHiStqfxdU3aenT261wcFZXWVk4vo9uQbKOz0pAhDYB7I',
    ),
    'tout_admin' => 
    array (
      'kid' => 'tout_admin',
      'title' => '管理后台_超时时间',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'int',
      'dblen' => '255',
      'dbdef' => '1',
      'vreg' => 'n+d',
      'vtip' => '单位(时),建议1~4之间',
      'vmax' => '4',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'key' => 'tout_admin',
      'val' => '1',
    ),
    'tout_member' => 
    array (
      'kid' => 'tout_member',
      'title' => '会员_超时时间',
      'etab' => '0',
      'type' => 'input',
      'dbtype' => 'int',
      'dblen' => '255',
      'dbdef' => '4',
      'vreg' => 'n+d',
      'vtip' => '单位(时),建议1~4之间',
      'vmax' => '4',
      'fmsize' => '',
      'fmline' => '1',
      'fmtitle' => '0',
      'fmextra' => '',
      'fmexstr' => '',
      'cfgs' => '',
      'key' => 'tout_member',
      'val' => '4',
    ),
  ),
);
?>